### ISSUE TITLE
NGINX Host dont found

### ISSUE THREAD

**Issue by JhonathanJJGS** [Screenly/Anthias#1752]
#### Overview of the Issue

NGINX restarting all time in docker
Log:
nginx: [emerg] host not found in upstream "anthias-server:8080" in /etc/nginx/sites-enabled/srly-ose.conf 

#### Reproduction Steps

Brand new instalation via .sh script. 

#### Environment

* Raspberry Pi Hardware Version: 3
* Raspberry Pi Network Setup:Ethernet
* Anthias Version: Last version from install script 

Thanks!

**Comment by nicomiguelino** [comment]
Ideally, running `bin/upgrade_containers.sh` should work. Changes were added to the script so that services will be renamed from `srly-ose-*` to `anthias-*`. Here's the snippet:

```python
if [[ -n $(docker ps | grep srly-ose) ]]; then
    # @TODO: Rename later
    set +e
    docker container rename srly-ose-wifi-connect anthias-wifi-connect
    docker container rename srly-ose-server anthias-server
    docker container rename srly-ose-viewer anthias-viewer
    docker container rename srly-ose-celery anthias-celery
    docker container rename srly-ose-websocket anthias-websocket
    docker container rename srly-ose-nginx anthias-nginx
    set -e
fi
```

Thanks for raising this issue @JhonathanJJGS. What would the console output look like if you try running `docker compose ps` or `docker ps`?

**Comment by JhonathanJJGS** [comment]
Hmm maybe the file nginx.conf is not being copied inside de nginx container when i upgrade_container.sh, what do you think?
